/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package airlinereservation;

/**
 *
 * @author namphan
 */
public class AirlineFrame extends javax.swing.JFrame {

    /**
     * Creates new form AirlineFrame
     */
    public AirlineFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        seat1 = new javax.swing.JCheckBox();
        seat2 = new javax.swing.JCheckBox();
        seat3 = new javax.swing.JCheckBox();
        seat4 = new javax.swing.JCheckBox();
        seat5 = new javax.swing.JCheckBox();
        seat6 = new javax.swing.JCheckBox();
        seat7 = new javax.swing.JCheckBox();
        seat8 = new javax.swing.JCheckBox();
        seat9 = new javax.swing.JCheckBox();
        seat10 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        economyRadioButton = new javax.swing.JRadioButton();
        firtclassRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        seatCount1 = new javax.swing.JLabel();
        seatCount2 = new javax.swing.JLabel();
        seatComment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        airplaneFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 255, 255));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 310, 54, 60);

        seat1.setText("1");
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });
        getContentPane().add(seat1);
        seat1.setBounds(300, 160, 40, 40);

        seat2.setText("2");
        seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat2ActionPerformed(evt);
            }
        });
        getContentPane().add(seat2);
        seat2.setBounds(290, 230, 40, 40);

        seat3.setText("3");
        seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat3ActionPerformed(evt);
            }
        });
        getContentPane().add(seat3);
        seat3.setBounds(360, 230, 40, 40);

        seat4.setText("4");
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });
        getContentPane().add(seat4);
        seat4.setBounds(290, 300, 40, 40);

        seat5.setText("5");
        seat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat5ActionPerformed(evt);
            }
        });
        getContentPane().add(seat5);
        seat5.setBounds(370, 300, 40, 40);

        seat6.setText("6");
        seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat6ActionPerformed(evt);
            }
        });
        getContentPane().add(seat6);
        seat6.setBounds(290, 390, 40, 40);

        seat7.setText("7");
        seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat7ActionPerformed(evt);
            }
        });
        getContentPane().add(seat7);
        seat7.setBounds(370, 390, 40, 40);

        seat8.setText("8");
        seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat8ActionPerformed(evt);
            }
        });
        getContentPane().add(seat8);
        seat8.setBounds(300, 470, 40, 40);

        seat9.setText("9");
        seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat9ActionPerformed(evt);
            }
        });
        getContentPane().add(seat9);
        seat9.setBounds(370, 470, 40, 40);

        seat10.setText("10");
        seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat10ActionPerformed(evt);
            }
        });
        getContentPane().add(seat10);
        seat10.setBounds(330, 560, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 570, 60, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 240, 54, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("G4 AIRLINE ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 270, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 240, 54, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 310, 54, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 400, 54, 60);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 400, 54, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 480, 54, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 480, 54, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/seat.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 170, 60, 60);

        economyRadioButton.setText("ECONOMY (Seat 6-10)");
        economyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(economyRadioButton);
        economyRadioButton.setBounds(450, 170, 180, 23);

        firtclassRadioButton.setText("FIRST CLASS (Seat 1-5)");
        getContentPane().add(firtclassRadioButton);
        firtclassRadioButton.setBounds(450, 100, 175, 23);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("RESERVE ");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 70, 140, 60);

        seatCount1.setText("There are ... seats left ");
        getContentPane().add(seatCount1);
        seatCount1.setBounds(480, 120, 160, 20);

        seatCount2.setText("There are ... seats left ");
        getContentPane().add(seatCount2);
        seatCount2.setBounds(480, 190, 160, 20);

        seatComment.setText("comment when the seat full");
        getContentPane().add(seatComment);
        seatComment.setBounds(450, 290, 190, 30);

        jTextArea1.setBackground(java.awt.Color.yellow);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Please choose the Class.\n2. Click to pick the Seat.\n3. Press RESERVE to complete.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 510, 244, 110);

        jTextField1.setText("RESERVATION SUMMARY ");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 110, 190, 120);

        resetButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(153, 0, 153));
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(30, 579, 110, 40);

        airplaneFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/airplane.png"))); // NOI18N
        getContentPane().add(airplaneFrame);
        airplaneFrame.setBounds(0, 90, 680, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat1ActionPerformed

    private void seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat3ActionPerformed

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat4ActionPerformed

    private void seat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat5ActionPerformed

    private void seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat6ActionPerformed

    private void seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat7ActionPerformed

    private void seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat8ActionPerformed

    private void seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat9ActionPerformed

    private void seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat10ActionPerformed

    private void seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat2ActionPerformed

    private void economyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_economyRadioButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airplaneFrame;
    private javax.swing.JRadioButton economyRadioButton;
    private javax.swing.JRadioButton firtclassRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox seat1;
    private javax.swing.JCheckBox seat10;
    private javax.swing.JCheckBox seat2;
    private javax.swing.JCheckBox seat3;
    private javax.swing.JCheckBox seat4;
    private javax.swing.JCheckBox seat5;
    private javax.swing.JCheckBox seat6;
    private javax.swing.JCheckBox seat7;
    private javax.swing.JCheckBox seat8;
    private javax.swing.JCheckBox seat9;
    private javax.swing.JLabel seatComment;
    private javax.swing.JLabel seatCount1;
    private javax.swing.JLabel seatCount2;
    // End of variables declaration//GEN-END:variables
}
