
package unit6_airlinereservationsystem;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import unit6_airlinereservationsystem.Aircraft.Column;

/**
 *
 * @author namphan
 */
public class AirlineFrameGUI extends javax.swing.JFrame {

    private class SeatColorCode{
        private final Seat seat;
        private Color color;
        
        private SeatColorCode(Seat seat, Color color){
            this.seat = seat;
            this.color = color;
        }
        
        protected void setColor(Color color){
            this.color = color;
        }
        protected Seat getSeat(){
            return this.seat;
        }
        protected Color getColor(){
            return this.color;
        }
    }
    
    ConcurrentHashMap<JButton, SeatColorCode> buttonColorState = new ConcurrentHashMap<>(14, 3.0f, 3);
    JButton currentButtonSelected;
    JButton previousButtonSelected;
    TravelClass firstClass;
    TravelClass economyClass;
    List<TravelClass> pList = new ArrayList();
    AircraftFactory cessna = new Aircraft();
    ConcurrentHashMap<Aircraft.TypeOfTravelClass, TravelClass> createdTravelClasses;
            
    /**
     * Creates new form AirlineFrame
     */
    public AirlineFrameGUI() {
        this.initComponents();
        this.init();
        
        firstClass = new FirstClass(3,Column.B);
        economyClass = new EconomyClass(4, Column.B);
        
        pList.add(firstClass);
        pList.add(economyClass);
        
        createdTravelClasses = cessna.createTravelClass(pList);
        this.initButtonColorState();        

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTP_Main = new javax.swing.JTabbedPane();
        jP_Main = new javax.swing.JPanel();
        jLab_Title = new javax.swing.JLabel();
        jLab_AirFrame = new javax.swing.JLabel();
        jP_AirFrame = new javax.swing.JPanel();
        jP_Seats = new javax.swing.JPanel();
        jBtn_FC1 = new javax.swing.JButton();
        jBtn_FC2 = new javax.swing.JButton();
        jBtn_FC3 = new javax.swing.JButton();
        jBtn_FC4 = new javax.swing.JButton();
        jBtn_FC5 = new javax.swing.JButton();
        jBtn_FC6 = new javax.swing.JButton();
        jBtn_EC1 = new javax.swing.JButton();
        jBtn_EC2 = new javax.swing.JButton();
        jBtn_EC3 = new javax.swing.JButton();
        jBtn_EC4 = new javax.swing.JButton();
        jBtn_EC5 = new javax.swing.JButton();
        jBtn_EC6 = new javax.swing.JButton();
        jBtn_EC7 = new javax.swing.JButton();
        jBtn_EC8 = new javax.swing.JButton();
        jP_UserInputForm = new javax.swing.JPanel();
        jLbl_FirstName = new javax.swing.JLabel();
        jTF_FirstName = new javax.swing.JTextField();
        jLblLastName = new javax.swing.JLabel();
        jTF_LastName = new javax.swing.JTextField();
        jBtn_Submit = new javax.swing.JButton();
        jBtn_Clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_Msg = new javax.swing.JTextArea();
        jP_Passengers = new javax.swing.JPanel();

        resetButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(153, 0, 153));
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 255, 255));
        setForeground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(675, 710));

        jP_Main.setBackground(new java.awt.Color(255, 255, 255));
        jP_Main.setToolTipText("");
        jP_Main.setOpaque(false);

        jLab_Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLab_Title.setForeground(new java.awt.Color(153, 0, 0));
        jLab_Title.setText("G4 AIRLINES");
        jLab_Title.setToolTipText("");

        jLab_AirFrame.setBackground(new java.awt.Color(255, 255, 255));
        jLab_AirFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/airplane.png"))); // NOI18N
        jLab_AirFrame.setToolTipText("");
        jLab_AirFrame.setMaximumSize(new java.awt.Dimension(650, 610));
        jLab_AirFrame.setMinimumSize(new java.awt.Dimension(650, 610));
        jLab_AirFrame.setName(""); // NOI18N
        jLab_AirFrame.setPreferredSize(new java.awt.Dimension(650, 610));

        jP_AirFrame.setOpaque(false);
        jP_AirFrame.setPreferredSize(new java.awt.Dimension(660, 610));

        jP_Seats.setMaximumSize(new java.awt.Dimension(65, 550));
        jP_Seats.setName(""); // NOI18N
        jP_Seats.setOpaque(false);
        jP_Seats.setPreferredSize(new java.awt.Dimension(650, 550));

        jBtn_FC1.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_FC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/firstclass.png"))); // NOI18N
        jBtn_FC1.setMaximumSize(new java.awt.Dimension(80, 70));
        jBtn_FC1.setMinimumSize(new java.awt.Dimension(80, 70));
        jBtn_FC1.setPreferredSize(new java.awt.Dimension(80, 70));
        jBtn_FC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FC1ActionPerformed(evt);
            }
        });

        jBtn_FC2.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_FC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/firstclass.png"))); // NOI18N
        jBtn_FC2.setMaximumSize(new java.awt.Dimension(80, 70));
        jBtn_FC2.setMinimumSize(new java.awt.Dimension(80, 70));
        jBtn_FC2.setName(""); // NOI18N
        jBtn_FC2.setPreferredSize(new java.awt.Dimension(80, 70));
        jBtn_FC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FC2ActionPerformed(evt);
            }
        });

        jBtn_FC3.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_FC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/firstclass.png"))); // NOI18N
        jBtn_FC3.setMaximumSize(new java.awt.Dimension(80, 70));
        jBtn_FC3.setMinimumSize(new java.awt.Dimension(80, 70));
        jBtn_FC3.setPreferredSize(new java.awt.Dimension(80, 70));
        jBtn_FC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FC3ActionPerformed(evt);
            }
        });

        jBtn_FC4.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_FC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/firstclass.png"))); // NOI18N
        jBtn_FC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FC4ActionPerformed(evt);
            }
        });

        jBtn_FC5.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_FC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/firstclass.png"))); // NOI18N
        jBtn_FC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FC5ActionPerformed(evt);
            }
        });

        jBtn_FC6.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_FC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/firstclass.png"))); // NOI18N
        jBtn_FC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FC6ActionPerformed(evt);
            }
        });

        jBtn_EC1.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC1ActionPerformed(evt);
            }
        });

        jBtn_EC2.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC2ActionPerformed(evt);
            }
        });

        jBtn_EC3.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC3ActionPerformed(evt);
            }
        });

        jBtn_EC4.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC4ActionPerformed(evt);
            }
        });

        jBtn_EC5.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC5ActionPerformed(evt);
            }
        });

        jBtn_EC6.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC6ActionPerformed(evt);
            }
        });

        jBtn_EC7.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC7ActionPerformed(evt);
            }
        });

        jBtn_EC8.setBackground(new java.awt.Color(51, 240, 0));
        jBtn_EC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/seat.png"))); // NOI18N
        jBtn_EC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EC8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_SeatsLayout = new javax.swing.GroupLayout(jP_Seats);
        jP_Seats.setLayout(jP_SeatsLayout);
        jP_SeatsLayout.setHorizontalGroup(
            jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SeatsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_SeatsLayout.createSequentialGroup()
                        .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtn_EC1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_EC3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_EC4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jBtn_EC2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jP_SeatsLayout.createSequentialGroup()
                        .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtn_EC5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jBtn_EC7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtn_EC8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_EC6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SeatsLayout.createSequentialGroup()
                        .addComponent(jBtn_FC5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtn_FC4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_FC6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SeatsLayout.createSequentialGroup()
                        .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtn_FC3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jBtn_FC1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_FC2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jP_SeatsLayout.setVerticalGroup(
            jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SeatsLayout.createSequentialGroup()
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_FC2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_FC1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_FC3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_FC4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_FC6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_FC5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_EC2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_EC1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_EC4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_EC3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_EC6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_EC5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_EC7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_EC8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jP_UserInputForm.setOpaque(false);

        jLbl_FirstName.setText("Passenger's First Name:");

        jTF_FirstName.setText("First Name");
        jTF_FirstName.setToolTipText("Enter Passenger's First Name");
        jTF_FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_FirstNameFocusGained(evt);
            }
        });

        jLblLastName.setText("Passenger's Last Name:");

        jTF_LastName.setText("Last Name");
        jTF_LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_LastNameFocusGained(evt);
            }
        });

        jBtn_Submit.setText("Submit");
        jBtn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SubmitActionPerformed(evt);
            }
        });

        jBtn_Clear.setText("Clear");
        jBtn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ClearActionPerformed(evt);
            }
        });

        jScrollPane2.setOpaque(false);

        jTA_Msg.setEditable(false);
        jTA_Msg.setColumns(20);
        jTA_Msg.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTA_Msg.setRows(5);
        jTA_Msg.setOpaque(false);
        jScrollPane2.setViewportView(jTA_Msg);

        javax.swing.GroupLayout jP_UserInputFormLayout = new javax.swing.GroupLayout(jP_UserInputForm);
        jP_UserInputForm.setLayout(jP_UserInputFormLayout);
        jP_UserInputFormLayout.setHorizontalGroup(
            jP_UserInputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_UserInputFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_UserInputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF_FirstName)
                    .addComponent(jLblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP_UserInputFormLayout.createSequentialGroup()
                        .addComponent(jBtn_Submit)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_Clear)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_UserInputFormLayout.createSequentialGroup()
                        .addComponent(jTF_LastName)
                        .addGap(4, 4, 4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_UserInputFormLayout.setVerticalGroup(
            jP_UserInputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_UserInputFormLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jP_UserInputFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Submit)
                    .addComponent(jBtn_Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jP_AirFrameLayout = new javax.swing.GroupLayout(jP_AirFrame);
        jP_AirFrame.setLayout(jP_AirFrameLayout);
        jP_AirFrameLayout.setHorizontalGroup(
            jP_AirFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AirFrameLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jP_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_UserInputForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_AirFrameLayout.setVerticalGroup(
            jP_AirFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AirFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(jP_AirFrameLayout.createSequentialGroup()
                .addComponent(jP_UserInputForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_MainLayout = new javax.swing.GroupLayout(jP_Main);
        jP_Main.setLayout(jP_MainLayout);
        jP_MainLayout.setHorizontalGroup(
            jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_MainLayout.createSequentialGroup()
                .addComponent(jP_AirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_MainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLab_Title)
                .addGap(217, 217, 217))
            .addGroup(jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_MainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLab_AirFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        jP_MainLayout.setVerticalGroup(
            jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_MainLayout.createSequentialGroup()
                .addComponent(jLab_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jP_AirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_MainLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLab_AirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        jTP_Main.addTab("Reservation", jP_Main);

        jP_Passengers.setOpaque(false);

        javax.swing.GroupLayout jP_PassengersLayout = new javax.swing.GroupLayout(jP_Passengers);
        jP_Passengers.setLayout(jP_PassengersLayout);
        jP_PassengersLayout.setHorizontalGroup(
            jP_PassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jP_PassengersLayout.setVerticalGroup(
            jP_PassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        jTP_Main.addTab("Passenger List", jP_Passengers);

        getContentPane().add(jTP_Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void selectedButtonSetColor(JButton selectedButton){
        previousButtonSelected = currentButtonSelected;
        currentButtonSelected = selectedButton;

        selectedButton.setBackground(Color.blue);
        if (previousButtonSelected != null && previousButtonSelected != currentButtonSelected) {
            previousButtonSelected.setBackground(this.buttonColorState.get(previousButtonSelected).getColor());
        }
    }
    // FIRST CLASS
    
    
    private void jBtn_FC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FC1ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_FC1ActionPerformed

    private void jBtn_FC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FC2ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_FC2ActionPerformed

    private void jBtn_FC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FC3ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_FC3ActionPerformed

    private void jBtn_FC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FC4ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_FC4ActionPerformed

    private void jBtn_FC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FC5ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_FC5ActionPerformed

    private void jBtn_FC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FC6ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_FC6ActionPerformed

    // ECONOMY CLASS
    
    /**
     * 
     * @param evt 
     */
    private void jBtn_EC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC1ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC1ActionPerformed

    private void jBtn_EC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC2ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC2ActionPerformed

    private void jBtn_EC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC3ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC3ActionPerformed

    private void jBtn_EC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC4ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC4ActionPerformed

    private void jBtn_EC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC5ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC5ActionPerformed

    private void jBtn_EC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC6ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC6ActionPerformed

    private void jBtn_EC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC7ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC7ActionPerformed

    private void jBtn_EC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EC8ActionPerformed
        this.selectedButtonSetColor((JButton)evt.getSource());
    }//GEN-LAST:event_jBtn_EC8ActionPerformed

    private void jBtn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SubmitActionPerformed
        JButton _selectedButton = this.currentButtonSelected;
        TravelClass _travelClass;
        SeatColorCode _sc;
        Seat _seat;
        String _firstName;
        String _lastName;
        int _row;
        Column _column;
        
        if (this.currentButtonSelected == null) {
            this.jTA_Msg.setText("No Seat Selected\nSelect a seat");
            return;
        }
        
        _sc = this.buttonColorState.get(_selectedButton);
        _seat = _sc.getSeat();
        _firstName = this.jTF_FirstName.getText();
        _lastName = this.jTF_LastName.getText();
        _row = _seat.getSeatRow();
        _column = _seat.getSeatColumn();
        
        if (_sc.getColor() == Color.RED) {
            this.jTA_Msg.setText(String.format("That Seat is Taken%nSeat Row#:%d Column: %s%nSelect Another seat", _row, _column));
            return;
        }
        
        if( _seat.getSeatClass() instanceof FirstClass){
            _travelClass = (FirstClass) createdTravelClasses.get(Aircraft.TypeOfTravelClass.FIRSTCLASS);
            _travelClass.placeResearvation(_row,_column, new Passenger(_firstName, _lastName));
            _sc.setColor(Color.RED);
        }
        
        if( _seat.getSeatClass() instanceof EconomyClass){
            _travelClass = (EconomyClass) createdTravelClasses.get(Aircraft.TypeOfTravelClass.ECONOMYCLASS);
            _travelClass.placeResearvation(_row,_column, new Passenger(_firstName, _lastName));
            _sc.setColor(Color.RED);
        }        
    }//GEN-LAST:event_jBtn_SubmitActionPerformed

    private void jBtn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ClearActionPerformed
       this.jTF_FirstName.setText("First Name");
       this.jTF_LastName.setText("Last Name");
    }//GEN-LAST:event_jBtn_ClearActionPerformed

    private void jTF_FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_FirstNameFocusGained
       this.jTF_FirstName.setText("");
    }//GEN-LAST:event_jTF_FirstNameFocusGained

    private void jTF_LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_LastNameFocusGained
        this.jTF_LastName.setText("");
    }//GEN-LAST:event_jTF_LastNameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
        //        new AirlineFrameGUI().setVisible(true);
        //    }
        //});
    }

        /**
     * Initialize some properties of the JFrame Component and make it visible
     */
    private void init() {
        JPanel panel_main = new BackGround(this, "background_main.jpg");       
        panel_main.add(this.jTP_Main, BorderLayout.NORTH);
        
        this.setContentPane(panel_main);
          
        this.setTitle("G4 Airline Reservation");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(660, 680);           // Size the JFrame to a known size configuration
        this.setLocationRelativeTo(null); // Brings the window to the Center of the screen
        this.setVisible(true);            // Vital allow visibility of the JFrame NB: JFrame.show() is deprecated 
    }
    
    private void initButtonColorState() {
        final AirlineFrameGUI e = this;
        Map<JButton, SeatColorCode> _buttonColorState = new HashMap<JButton, SeatColorCode>(){
            {
                put(e.jBtn_FC1, new SeatColorCode(new Seat(firstClass, 1, Column.A), Color.GREEN));
                put(e.jBtn_FC2, new SeatColorCode(new Seat(firstClass, 1, Column.B), Color.GREEN));
                put(e.jBtn_FC3, new SeatColorCode(new Seat(firstClass, 2, Column.A), Color.GREEN));
                put(e.jBtn_FC4, new SeatColorCode(new Seat(firstClass, 2, Column.B), Color.GREEN));           
                put(e.jBtn_FC5, new SeatColorCode(new Seat(firstClass, 3, Column.A), Color.GREEN));
                put(e.jBtn_FC6, new SeatColorCode(new Seat(firstClass, 3, Column.B), Color.GREEN));           
                put(e.jBtn_EC1, new SeatColorCode(new Seat(economyClass, 1, Column.A), Color.GREEN));
                put(e.jBtn_EC2, new SeatColorCode(new Seat(economyClass, 1, Column.B), Color.GREEN));
                put(e.jBtn_EC3, new SeatColorCode(new Seat(economyClass, 2, Column.A), Color.GREEN));
                put(e.jBtn_EC4, new SeatColorCode(new Seat(economyClass, 2, Column.B), Color.GREEN));         
                put(e.jBtn_EC5, new SeatColorCode(new Seat(economyClass, 3, Column.A), Color.GREEN));
                put(e.jBtn_EC6, new SeatColorCode(new Seat(economyClass, 3, Column.B), Color.GREEN));
                put(e.jBtn_EC7, new SeatColorCode(new Seat(economyClass, 4, Column.A), Color.GREEN));
                put(e.jBtn_EC8, new SeatColorCode(new Seat(economyClass, 4, Column.B), Color.GREEN));
            }
        };
        buttonColorState.putAll(_buttonColorState);
    }//end initButtonColorState
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Clear;
    private javax.swing.JButton jBtn_EC1;
    private javax.swing.JButton jBtn_EC2;
    private javax.swing.JButton jBtn_EC3;
    private javax.swing.JButton jBtn_EC4;
    private javax.swing.JButton jBtn_EC5;
    private javax.swing.JButton jBtn_EC6;
    private javax.swing.JButton jBtn_EC7;
    private javax.swing.JButton jBtn_EC8;
    private javax.swing.JButton jBtn_FC1;
    private javax.swing.JButton jBtn_FC2;
    private javax.swing.JButton jBtn_FC3;
    private javax.swing.JButton jBtn_FC4;
    private javax.swing.JButton jBtn_FC5;
    private javax.swing.JButton jBtn_FC6;
    private javax.swing.JButton jBtn_Submit;
    private javax.swing.JLabel jLab_AirFrame;
    private javax.swing.JLabel jLab_Title;
    private javax.swing.JLabel jLblLastName;
    private javax.swing.JLabel jLbl_FirstName;
    private javax.swing.JPanel jP_AirFrame;
    private javax.swing.JPanel jP_Main;
    private javax.swing.JPanel jP_Passengers;
    private javax.swing.JPanel jP_Seats;
    private javax.swing.JPanel jP_UserInputForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA_Msg;
    private javax.swing.JTextField jTF_FirstName;
    private javax.swing.JTextField jTF_LastName;
    private javax.swing.JTabbedPane jTP_Main;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
